name: Upload Artifact to Azure
on:
    push:
        branches-ignore:
            - master
    workflow_dispatch:


jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-storage-blob

      - name: Upload to Azure
        env:
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
        run: |
          python upload_to_azure.py "$AZURE_CONNECTION_STRING" "$CONTAINER_NAME" "artifact" "${{ github.ref_name }}"